# Generated by Django 4.0.6 on 2022-11-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0002_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='track',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
