# Generated by Django 4.0.6 on 2022-11-04 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0005_alter_run_date_alter_run_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
