# Generated by Django 4.0.6 on 2022-11-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0007_remove_run_pace'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='pace',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
